name: Leads Academy CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag leadsacademydemo
    - name: Get short SHA
      id: sha
      run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Build and Push to ECR public
      id: build-and-push
      uses: pahud/ecr-public-action@8cd826db40befb59b0cd0b60b22a7ba72d06a7f7
      with:
        tags: |
          public.ecr.aws/j3q3x4x2/leadsacademydemo:latest
          public.ecr.aws/j3q3x4x2/leadsacademydemo:${{ steps.sha.outputs.sha7 }}

  deploy:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - run: whoami
    - name: Pull image update
      run: docker pull public.ecr.aws/j3q3x4x2/leadsacademydemo:latest
    - name: Run Container
      run: |
        sudo docker rm -f leadsacademydemo
        sudo docker run -dit -p 80:5000 --name leadsacademydemo public.ecr.aws/j3q3x4x2/leadsacademydemo:latest
    - name: Cleanup
      run: sudo docker system prune -f