name: Leads Academy CI

on:
  push:
    branches: [ "hands-on-lab" ]
    tags:        
      - '**' 

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          echo npm install --silent
          echo npm install react-scripts@3.4.1 -g --silent
          echo CI=true npm test
      
  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get short SHA
      id: sha
      run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build Finish
      run : echo "Build Demo Finished !"

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: whoami
    - name: Pull image update
      run: echo "Deploying application in progress ...."
    - name: Run Container
      run: |
        echo sudo docker rm -f leadsacademydemo
        echo sudo docker run -dit -p 8081:3000 --name leadsacademydemo public.ecr.aws/j3q3x4x2/leadsacademydemo:latest
    - name: Cleanup
      run: echo sudo docker system prune -f
